### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by cabalerdw** [Livin21/MissMe#7]
I added this lib to my project, and now it's giving this error, has anyone ever gone through it?

> gradlew assemble
> 
> > Configure project :app
> 
> C:\Users\cabalerdw\.gradle\caches\transforms-1\files-1.1\missme-0.1.5.aar\6ce5d64647
> 097d315db9d1ebfff3a8b6\res\layout\horizontal_progress_dialog.xml:34: AAPT: error
> : attribute cardCornerRadius (aka com.myproject.app:cardCornerRadius) n
> ot found.
> 
> C:\Users\cabalerdw\.gradle\caches\transforms-1\files-1.1\missme-0.1.5.aar\6ce5d64647
> 097d315db9d1ebfff3a8b6\res\layout\horizontal_progress_dialog.xml:34: AAPT: error
> : attribute cardElevation (aka com.myproject.app:cardElevation) not fou
> nd.
> 
> C:\Users\cabalerdw\.gradle\caches\transforms-1\files-1.1\missme-0.1.5.aar\6ce5d64647
> 097d315db9d1ebfff3a8b6\res\layout\spinner_progress_dialog.xml:34: AAPT: error: a
> ttribute cardElevation (aka com.myproject.app:cardElevation) not found.
> 
> 
> error: failed linking file resources.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Failed to process resources, see aapt output above for details.
> 
>

**Comment by Livin21** [comment]
Try adding these dependencies.
```
implementation 'com.android.support:cardview-v7:26.1.0' 
implementation 'com.android.support:appcompat-v7:26.1.0'
```
